[definitions.direction]
name = "方向"
unique = "direction"
defaultValue = 'vertical'
[[definitions.direction.options]]
name = "垂直"
unique = "vertical"
[[definitions.direction.options]]
name = "水平"
unique = "horizontal"

[schema.layout]
children = [
  'layout',
  'form',
  'toolbar',
]
name = "布局"
[[schema.layout.values]]
ref = "definitions.direction"

[schema.form]
children = [
  'form-item',
]
name = "表单"

[schema.toolbar]
children = [
  'button',
  'form-item',
]
name = "工具栏"

[schema.form-item]
name = "输入"

[schema.button]
name = "按钮"
