[definitions.direction]
name = "方向"
kind = "select"
unique = "direction"
defaultValue = 'vertical'
[[definitions.direction.options]]
label = "垂直"
value = "vertical"
[[definitions.direction.options]]
label = "水平"
value = "horizontal"

[schema.root]
name = "画布"
children = [
  'form',
  'toolbar',
  'data-table',
  'layout',
]
[[schema.root.properties]]
ref = "definitions.direction"

[schema.form]
name = "查询表单"
children = [
  'form-item',
]
[[schema.form.properties]]
name = "列数"
kind = "number"
unique = "rows"
defaultValue = 4

[schema.toolbar]
name = "工具栏"
children = [
  'button',
  'form-item',
]

[schema.data-table]
name = "数据表格"

[schema.chart]
name = "图表"

[schema.layout]
name = "布局/分组"
children = [
  'form',
  'toolbar',
  'data-table',
]
[[schema.layout.properties]]
ref = "definitions.direction"

[schema.form-item]
name = "输入"

[schema.button]
name = "按钮"
