component = "Bigscreen"

[[children]]
component = "Container"
[children.style]
display = "flex"

[[children.children]]
component = "Chart"
data = ["ajaxGet", "/mock/series.mock.v1.json", "data"]
[children.children.config]
height = 300
width = 260
[children.children.chart]
type = "bar"
axis = ["label", "value"]

[[children.children]]
component = "Chart"
data = ["ajaxGet", "/mock/series.mock.v2.json", "data"]
[children.children.config]
height = 300
width = 260
[children.children.chart]
type = "line"
axis = ["month", "temperature"]
extra = [["mark"]]
group = "city"


[[children.children]]
component = "Chart"
data = ["ajaxGet", "/mock/series.mock.v4.json", "data"]
[children.children.config]
height = 300
width = 260
[children.children.chart]
type = "bar"
axis = ["time", "value"]
group = "type"


[[children.children]]
component = "Chart"
data = ["ajaxGet", "/mock/series.mock.v4.json", "data"]
[children.children.config]
height = 300
width = 260
[children.children.chart]
type = "pie"
axis = ["value"]
group = "type"

[[children.children]]
component = "Chart"
data = ["ajaxGet", "/mock/series.mock.v3.json", "data"]
[children.children.config]
height = 300
width = 260
[children.children.chart]
type = "line"
axis = ["year", "value"]
extra = [["area"]]

[[children]]
component = "Container"
[children.style]
display = "flex"

[[children.children]]
component = "Datagrid"
[children.children.style]
flex = 1

[[children.children]]
component = "Datagrid"
[children.children.style]
flex = 1

[[children.children]]
component = "Datagrid"
[children.children.style]
flex = 1
