component = "Bigscreen"

[[children]]
component = "Container"
[children.style]
display = "flex"

[[children.children]]
component = "Chart"
request = ["get", "/mock/series.mock.v1.json"]
[children.children.config]
height = 300
width = 260
type = "bar"
axis = ["label", "value"]

[[children.children]]
component = "Chart"
request = ["get", "/mock/series.mock.v2.json"]
[children.children.config]
height = 300
width = 260
type = "line"
axis = ["month", "temperature"]
group = "city"
extra = [["mark"]]

[[children.children]]
component = "Chart"
request = ["get", "/mock/series.mock.v4.json"]
[children.children.config]
height = 300
width = 260
type = "bar"
axis = ["time", "value"]
group = "type"

[[children.children]]
component = "Chart"
request = ["get", "/mock/series.mock.v4.json"]
[children.children.config]
height = 300
width = 260
type = "pie"
axis = ["value"]
group = "type"

[[children.children]]
component = "Chart"
request = ["get", "/mock/series.mock.v3.json"]
[children.children.config]
height = 300
width = 260
type = "line"
axis = ["year", "value"]
smooth = false
extra = [["area"]]

[[children]]
component = "Toolbar"
[[children.children]]
component = "button"
text = "L1"
[[children.children]]
component = "button"
text = "L2"
[[children.children]]
component = "button"
place = "right"
text = "R1"
[[children.children]]
component = "button"
place = "right"
text = "R2"
[[children.children]]
component = "button"
place = "right"
text = "R3"

[[children]]
component = "Container"
[children.style]
display = "flex"

[[children.children]]
component = "Datagrid"
[children.children.style]
flex = 1

[[children.children]]
component = "Datagrid"
[children.children.style]
flex = 1

[[children.children]]
component = "Datagrid"
[children.children.style]
flex = 1
