layout = "query-list"
component = "Container"

[[children]]
component = "Form"

[[children.children]]
component = "FormControl"
label = "测试字段_A"

[[children.children]]
component = "FormControl"
label = "测试字段_B"

[[children.children]]
component = "FormControl"
label = "测试字段_C"

[[children]]
component = "Toolbar"

[[children.children]]
component = "button"
text = "确定"

[[children.children]]
component = "button"
text = "确定"

[[children]]
component = "Datagrid"