name = "vega-lite-v2"
# https://vega.github.io/vega-lite/docs/spec.html
schema = "https://vega.github.io/schema/vega/v5.json"

[[rules]]
unique = "title"

[[rules]]
unique = "marks"

[[rules]]
unique = "layouts"

[[rules]]
unique = "data.format"

[[rules]]
unique = "data.values"

[[rules]]
unique = "data.url"