name = "vega-lite-v2"
# https://vega.github.io/vega-lite/docs/spec.html
schema = "https://vega.github.io/schema/vega/v5.json"

title = "title"

marks = "marks"

[data]
format = "format"
source = "source"
url = "url"
values = "values"


