title = "Hello, world!"
kind = "root"

[[properties]]
unique = "datasource"
value = "/build/hello_table.json"

[[children]]
kind = "form"
[[children.properties]]
unique = "columns"
value = 4

[[children.children]]
kind = "form-item"
unique = "name"
label = "单据类型"
[[children.children.properties]]
unique = "kind"
value = "select"
[[children.children.properties.children]]
unique = "a"
label = "测试A"
[[children.children.properties.children]]
unique = "b"
label = "测试B"
[[children.children.properties.children]]
unique = "c"
label = "测试C"

[[children.children]]
kind = "form-item"
unique = "code"
label = "订单编号"
[[children.children.properties]]
unique = "kind"
value = "text"

[[children.children]]
kind = "form-item"
unique = "date"
label = "单据日期"
[[children.children.properties]]
unique = "kind"
value = "date"

[[children.children]]
kind = "form-item"
unique = "status"
label = "状态"
[[children.children.properties]]
unique = "kind"
value = "select"
[[children.children.properties.children]]
unique = "a"
label = "测试A"
[[children.children.properties.children]]
unique = "b"
label = "测试B"
[[children.children.properties.children]]
unique = "c"
label = "测试C"


[[children.children]]
kind = "form-item"
unique = "status_a"
label = "状态A"
[[children.children.properties]]
unique = "kind"
value = "select"
[[children.children.properties.children]]
unique = "a"
label = "测试A"
[[children.children.properties.children]]
unique = "b"
label = "测试B"
[[children.children.properties.children]]
unique = "c"
label = "测试C"


[[children.children]]
kind = "form-item"
unique = "status_b"
label = "状态B"
[[children.children.properties]]
unique = "kind"
value = "select"
[[children.children.properties.children]]
unique = "a"
label = "测试A"
[[children.children.properties.children]]
unique = "b"
label = "测试B"
[[children.children.properties.children]]
unique = "c"
label = "测试C"


[[children.children]]
kind = "form-item"
unique = "status_c"
label = "状态C"
[[children.children.properties]]
unique = "kind"
value = "select"
[[children.children.properties.children]]
unique = "a"
label = "测试A"
[[children.children.properties.children]]
unique = "b"
label = "测试B"
[[children.children.properties.children]]
unique = "c"
label = "测试C"


[[children.children]]
kind = "form-item"
unique = "status_d"
label = "状态D"
[[children.children.properties]]
unique = "kind"
value = "select"
[[children.children.properties.children]]
unique = "a"
label = "测试A"
[[children.children.properties.children]]
unique = "b"
label = "测试B"
[[children.children.properties.children]]
unique = "c"
label = "测试C"


[[children]]
kind = "toolbar"
[[children.children]]
label = "查询"
bind = "query"

[[children.children]]
label = "重置"
bind = "reset"

[[children.children]]
label = "高级搜索"
bind = "full_form"

[[children.children]]
label = "列设置"
bind = "set_columns"

[[children.children]]
label = "导出"
bind = "export"
place = "right"

[[children.children]]
label = "批量删除"
bind = "remove"
place = "right"

[[children]]
kind = "table"
[[children.properties]]

# seq 1 9 | awk '{                              \
#   print "[[children.children]]";    \
#   print "label = \"列"$1"\"";                 \
#   print "unique = \"column_" $1 "\""          \
# }'
[[children.children]]
label = "列1"
unique = "column_1"
[[children.children]]
label = "列2"
unique = "column_2"
[[children.children]]
label = "列3"
unique = "column_3"
[[children.children]]
label = "列4"
unique = "column_4"
[[children.children]]
label = "列5"
unique = "column_5"
[[children.children]]
label = "列6"
unique = "column_6"
[[children.children]]
label = "列7"
unique = "column_7"
[[children.children]]
label = "列8"
unique = "column_8"
[[children.children]]
label = "列9"
unique = "column_9"