title = "series.mock.v1"

[[data]]
label = "衬衫"
value = 5
[[data]]
label = "羊毛衫"
value = 20
[[data]]
label = "雪纺衫"
value = 36
[[data]]
label = "裤子"
value = 10
[[data]]
label = "高跟鞋"
value = 5
[[data]]
label = "袜子"
value = 20
