title = "基础面积图"
url = "https://antv-g2.gitee.io/zh/examples/area/basic#basic"

[[data]]
year = '1991'
value = 15468

[[data]]
year = '1992'
value = 16100

[[data]]
year = '1993'
value = 15900

[[data]]
year = '1994'
value = 17409

[[data]]
year = '1995'
value = 17000

[[data]]
year = '1996'
value = 31056

[[data]]
year = '1997'
value = 31982

[[data]]
year = '1998'
value = 32040

[[data]]
year = '1999'
value = 33233
