title = "零钱管家 APP 收支占比趋势分析"
url = "https://antv-g2.gitee.io/zh/examples/case/column#column10"

[[data]]
time = '03-19'
type = '101-1000'
value = 32000

[[data]]
time = '03-19'
type = '31-100'
value = 30000

[[data]]
time = '03-19'
type = '11-30'
value = 27000

[[data]]
time = '03-19'
type = '1-10'
value = 24000

[[data]]
time = '03-20'
type = '101-1000'
value = 35000

[[data]]
time = '03-20'
type = '31-100'
value = 32000

[[data]]
time = '03-20'
type = '11-30'
value = 30000

[[data]]
time = '03-20'
type = '1-10'
value = 27000

[[data]]
time = '03-21'
type = '101-1000'
value = 39000

[[data]]
time = '03-21'
type = '31-100'
value = 37000

[[data]]
time = '03-21'
type = '11-30'
value = 34000

[[data]]
time = '03-21'
type = '1-10'
value = 30000

[[data]]
time = '03-22'
type = '101-1000'
value = 44000

[[data]]
time = '03-22'
type = '31-100'
value = 42000

[[data]]
time = '03-22'
type = '11-30'
value = 38000

[[data]]
time = '03-22'
type = '1-10'
value = 34000

[[data]]
time = '03-23'
type = '101-1000'
value = 47000

[[data]]
time = '03-23'
type = '31-100'
value = 44000

[[data]]
time = '03-23'
type = '11-30'
value = 40000

[[data]]
time = '03-23'
type = '1-10'
value = 36000

[[data]]
time = '03-24'
type = '101-1000'
value = 48000

[[data]]
time = '03-24'
type = '31-100'
value = 46000

[[data]]
time = '03-24'
type = '11-30'
value = 42000

[[data]]
time = '03-24'
type = '1-10'
value = 38000

[[data]]
time = '03-25'
type = '101-1000'
value = 50000

[[data]]
time = '03-25'
type = '31-100'
value = 48000

[[data]]
time = '03-25'
type = '11-30'
value = 44000

[[data]]
time = '03-25'
type = '1-10'
value = 38000
