title = "series.mock.v2"

[[data]]
city = 'Tokyo'
month = 'Jan'
temperature = 7

[[data]]
city = 'London'
month = 'Jan'
temperature = 3.9

[[data]]
city = 'Tokyo'
month = 'Feb'
temperature = 6.9

[[data]]
city = 'London'
month = 'Feb'
temperature = 4.2

[[data]]
city = 'Tokyo'
month = 'Mar'
temperature = 9.5

[[data]]
city = 'London'
month = 'Mar'
temperature = 5.7

[[data]]
city = 'Tokyo'
month = 'Apr'
temperature = 14.5

[[data]]
city = 'London'
month = 'Apr'
temperature = 8.5

[[data]]
city = 'Tokyo'
month = 'May'
temperature = 18.4

[[data]]
city = 'London'
month = 'May'
temperature = 11.9

[[data]]
city = 'Tokyo'
month = 'Jun'
temperature = 21.5

[[data]]
city = 'London'
month = 'Jun'
temperature = 15.2

[[data]]
city = 'Tokyo'
month = 'Jul'
temperature = 25.2

[[data]]
city = 'London'
month = 'Jul'
temperature = 17

[[data]]
city = 'Tokyo'
month = 'Aug'
temperature = 26.5

[[data]]
city = 'London'
month = 'Aug'
temperature = 16.6

[[data]]
city = 'Tokyo'
month = 'Sep'
temperature = 23.3

[[data]]
city = 'London'
month = 'Sep'
temperature = 14.2

[[data]]
city = 'Tokyo'
month = 'Oct'
temperature = 18.3

[[data]]
city = 'London'
month = 'Oct'
temperature = 10.3

[[data]]
city = 'Tokyo'
month = 'Nov'
temperature = 13.9

[[data]]
city = 'London'
month = 'Nov'
temperature = 6.6

[[data]]
city = 'Tokyo'
month = 'Dec'
temperature = 9.6

[[data]]
city = 'London'
month = 'Dec'
temperature = 4.8
